// Catalogue organisé par rayons, comme dans un supermarché.
// Chaque produit a une catégorie ("category") qui sert à le classer.
// Modifiez librement cette liste pour refléter les vrais produits de votre magasin.

let CATEGORIES = [
  { id: "fruits", name: "Fruits", emoji: "🍎" },
  { id: "legumes", name: "Légumes", emoji: "🥬" },
  { id: "charcuterie", name: "Charcuterie", emoji: "🥓" },
  { id: "poissonnerie", name: "Poissonnerie", emoji: "🐟" },
  { id: "fromages", name: "Fromages", emoji: "🧀" },
  { id: "beurres-cremes", name: "Beurres, Crèmes, Margarines", emoji: "🧈" },
  { id: "laits-oeufs", name: "Laits et Œufs", emoji: "🥛" },
  { id: "yaourts", name: "Yaourts, Fromages blancs", emoji: "🍦" },
  { id: "desserts", name: "Desserts", emoji: "🍮" },
  { id: "epicerie-salee", name: "Épicerie salée", emoji: "🥫" },
  { id: "conserves", name: "Conserves", emoji: "🥫" },
  { id: "epicerie-sucree", name: "Épicerie sucrée", emoji: "🍫" },
  { id: "boissons", name: "Boissons", emoji: "🥤" },
  { id: "surgeles", name: "Surgelés", emoji: "🧊" },
  { id: "hygiene", name: "Hygiène & Beauté", emoji: "🧴" },
  { id: "entretien", name: "Entretien", emoji: "🧽" },
  { id: "boulangerie", name: "Boulangerie", emoji: "🍞" },
];

let PRODUCTS = [
  // Fruits
  { id: "1", name: "Pommes Golden", priceCents: 290, unit: "kg", emoji: "🍎", category: "fruits" },
  { id: "2", name: "Pommes Gala", priceCents: 310, unit: "kg", emoji: "🍎", category: "fruits" },
  { id: "3", name: "Bananes", priceCents: 180, unit: "kg", emoji: "🍌", category: "fruits" },
  { id: "4", name: "Poires", priceCents: 320, unit: "kg", emoji: "🍐", category: "fruits" },
  { id: "5", name: "Oranges", priceCents: 270, unit: "kg", emoji: "🍊", category: "fruits" },
  { id: "6", name: "Mandarines", priceCents: 340, unit: "kg", emoji: "🍊", category: "fruits" },
  { id: "7", name: "Clémentines", priceCents: 330, unit: "kg", emoji: "🍊", category: "fruits" },
  { id: "8", name: "Citrons", priceCents: 290, unit: "kg", emoji: "🍋", category: "fruits" },
  { id: "9", name: "Citrons verts", priceCents: 320, unit: "kg", emoji: "🍋", category: "fruits" },
  { id: "10", name: "Pamplemousses", priceCents: 150, unit: "unité", emoji: "🍊", category: "fruits" },
  { id: "11", name: "Kiwis", priceCents: 390, unit: "kg", emoji: "🥝", category: "fruits" },
  { id: "12", name: "Fraises", priceCents: 350, unit: "barquette", emoji: "🍓", category: "fruits" },
  { id: "13", name: "Framboises", priceCents: 420, unit: "barquette", emoji: "🍓", category: "fruits" },
  { id: "14", name: "Myrtilles", priceCents: 450, unit: "barquette", emoji: "🫐", category: "fruits" },
  { id: "15", name: "Raisin blanc", priceCents: 450, unit: "kg", emoji: "🍇", category: "fruits" },
  { id: "16", name: "Raisin noir", priceCents: 460, unit: "kg", emoji: "🍇", category: "fruits" },
  { id: "17", name: "Pêches", priceCents: 380, unit: "kg", emoji: "🍑", category: "fruits" },
  { id: "18", name: "Nectarines", priceCents: 390, unit: "kg", emoji: "🍑", category: "fruits" },
  { id: "19", name: "Abricots", priceCents: 420, unit: "kg", emoji: "🍑", category: "fruits" },
  { id: "20", name: "Prunes", priceCents: 350, unit: "kg", emoji: "🍑", category: "fruits" },
  { id: "21", name: "Cerises", priceCents: 590, unit: "kg", emoji: "🍒", category: "fruits" },
  { id: "22", name: "Melon", priceCents: 290, unit: "unité", emoji: "🍈", category: "fruits" },
  { id: "23", name: "Pastèque", priceCents: 490, unit: "unité", emoji: "🍉", category: "fruits" },
  { id: "24", name: "Ananas", priceCents: 320, unit: "unité", emoji: "🍍", category: "fruits" },
  { id: "25", name: "Mangue", priceCents: 250, unit: "unité", emoji: "🥭", category: "fruits" },
  { id: "26", name: "Avocat", priceCents: 190, unit: "unité", emoji: "🥑", category: "fruits" },
  { id: "27", name: "Grenade", priceCents: 290, unit: "unité", emoji: "🍎", category: "fruits" },
  { id: "28", name: "Litchi", priceCents: 390, unit: "barquette", emoji: "🍒", category: "fruits" },
  { id: "29", name: "Groseilles", priceCents: 350, unit: "barquette", emoji: "🍒", category: "fruits" },
  { id: "30", name: "Physalis", priceCents: 390, unit: "barquette", emoji: "🍒", category: "fruits" },

  // Légumes
  { id: "31", name: "Tomates", priceCents: 250, unit: "kg", emoji: "🍅", category: "legumes" },
  { id: "32", name: "Tomates cerises", priceCents: 290, unit: "barquette", emoji: "🍅", category: "legumes" },
  { id: "33", name: "Concombre", priceCents: 130, unit: "unité", emoji: "🥒", category: "legumes" },
  { id: "34", name: "Courgettes", priceCents: 240, unit: "kg", emoji: "🥒", category: "legumes" },
  { id: "35", name: "Aubergines", priceCents: 280, unit: "kg", emoji: "🍆", category: "legumes" },
  { id: "36", name: "Poivrons rouges", priceCents: 390, unit: "kg", emoji: "🫑", category: "legumes" },
  { id: "37", name: "Poivrons verts", priceCents: 350, unit: "kg", emoji: "🫑", category: "legumes" },
  { id: "38", name: "Carottes", priceCents: 150, unit: "kg", emoji: "🥕", category: "legumes" },
  { id: "39", name: "Pommes de terre", priceCents: 190, unit: "kg", emoji: "🥔", category: "legumes" },
  { id: "40", name: "Patates douces", priceCents: 290, unit: "kg", emoji: "🍠", category: "legumes" },
  { id: "41", name: "Oignons", priceCents: 160, unit: "kg", emoji: "🧅", category: "legumes" },
  { id: "42", name: "Échalotes", priceCents: 390, unit: "kg", emoji: "🧅", category: "legumes" },
  { id: "43", name: "Ail", priceCents: 150, unit: "sachet", emoji: "🧄", category: "legumes" },
  { id: "44", name: "Salade batavia", priceCents: 120, unit: "unité", emoji: "🥬", category: "legumes" },
  { id: "45", name: "Salade iceberg", priceCents: 130, unit: "unité", emoji: "🥬", category: "legumes" },
  { id: "46", name: "Épinards", priceCents: 220, unit: "sachet", emoji: "🥬", category: "legumes" },
  { id: "47", name: "Mâche", priceCents: 250, unit: "sachet", emoji: "🥬", category: "legumes" },
  { id: "48", name: "Champignons de Paris", priceCents: 230, unit: "barquette", emoji: "🍄", category: "legumes" },
  { id: "49", name: "Brocoli", priceCents: 190, unit: "unité", emoji: "🥦", category: "legumes" },
  { id: "50", name: "Chou-fleur", priceCents: 220, unit: "unité", emoji: "🥦", category: "legumes" },
  { id: "51", name: "Chou vert", priceCents: 180, unit: "unité", emoji: "🥬", category: "legumes" },
  { id: "52", name: "Haricots verts", priceCents: 390, unit: "kg", emoji: "🫛", category: "legumes" },
  { id: "53", name: "Petits pois", priceCents: 350, unit: "kg", emoji: "🫛", category: "legumes" },
  { id: "54", name: "Radis", priceCents: 120, unit: "botte", emoji: "🥬", category: "legumes" },
  { id: "55", name: "Betteraves", priceCents: 210, unit: "kg", emoji: "🥔", category: "legumes" },
  { id: "56", name: "Céleri", priceCents: 190, unit: "unité", emoji: "🥬", category: "legumes" },
  { id: "57", name: "Fenouil", priceCents: 220, unit: "unité", emoji: "🥬", category: "legumes" },
  { id: "58", name: "Poireaux", priceCents: 240, unit: "kg", emoji: "🥬", category: "legumes" },
  { id: "59", name: "Persil", priceCents: 90, unit: "botte", emoji: "🌿", category: "legumes" },
  { id: "60", name: "Navets", priceCents: 170, unit: "kg", emoji: "🥔", category: "legumes" },

  // Charcuterie
  { id: "81", name: "Rillettes de volaille", priceCents: 280, unit: "unité", emoji: "🥫", category: "charcuterie" },
  { id: "82", name: "Terrine de canard", priceCents: 350, unit: "unité", emoji: "🥫", category: "charcuterie" },
  { id: "83", name: "Foie gras de canard", priceCents: 990, unit: "unité", emoji: "🥫", category: "charcuterie" },
  { id: "84", name: "Foie gras de canard entier", priceCents: 1490, unit: "unité", emoji: "🥫", category: "charcuterie" },
  { id: "85", name: "Jambon cru d'Espagne", priceCents: 590, unit: "unité", emoji: "🥓", category: "charcuterie" },
  { id: "86", name: "Jambon cru fumé", priceCents: 490, unit: "unité", emoji: "🥓", category: "charcuterie" },
  { id: "87", name: "Jambon blanc supérieur", priceCents: 390, unit: "unité", emoji: "🥓", category: "charcuterie" },
  { id: "88", name: "Jambon cuit sans couenne", priceCents: 420, unit: "unité", emoji: "🥓", category: "charcuterie" },
  { id: "89", name: "Lardons fumés", priceCents: 260, unit: "unité", emoji: "🥓", category: "charcuterie" },
  { id: "90", name: "Poitrine fumée tranchée", priceCents: 320, unit: "unité", emoji: "🥓", category: "charcuterie" },
  { id: "91", name: "Pâté de campagne", priceCents: 280, unit: "unité", emoji: "🥫", category: "charcuterie" },
  { id: "92", name: "Rillettes du Mans", priceCents: 290, unit: "unité", emoji: "🥫", category: "charcuterie" },
  { id: "93", name: "Terrine forestière", priceCents: 320, unit: "unité", emoji: "🥫", category: "charcuterie" },
  { id: "94", name: "Saucisses de Toulouse", priceCents: 390, unit: "unité", emoji: "🌭", category: "charcuterie" },
  { id: "95", name: "Boudin noir", priceCents: 320, unit: "unité", emoji: "🌭", category: "charcuterie" },
  { id: "96", name: "Knacks", priceCents: 290, unit: "unité", emoji: "🌭", category: "charcuterie" },
  { id: "97", name: "Saucisson sec nature", priceCents: 420, unit: "unité", emoji: "🌭", category: "charcuterie" },
  { id: "98", name: "Saucisson sec aux noix", priceCents: 450, unit: "unité", emoji: "🌭", category: "charcuterie" },
  { id: "99", name: "Andouille de Vire", priceCents: 390, unit: "unité", emoji: "🌭", category: "charcuterie" },
  { id: "100", name: "Blanc de volaille fumé", priceCents: 350, unit: "unité", emoji: "🥓", category: "charcuterie" },

  // Poissonnerie
  { id: "101", name: "Saumon frais", priceCents: 1290, unit: "kg", emoji: "🐟", category: "poissonnerie" },
  { id: "102", name: "Saumon fumé", priceCents: 590, unit: "unité", emoji: "🐟", category: "poissonnerie" },
  { id: "103", name: "Cabillaud", priceCents: 1490, unit: "kg", emoji: "🐟", category: "poissonnerie" },
  { id: "104", name: "Colin", priceCents: 1190, unit: "kg", emoji: "🐟", category: "poissonnerie" },
  { id: "105", name: "Truite", priceCents: 590, unit: "unité", emoji: "🐟", category: "poissonnerie" },
  { id: "106", name: "Bar", priceCents: 1890, unit: "kg", emoji: "🐟", category: "poissonnerie" },
  { id: "107", name: "Dorade", priceCents: 1690, unit: "kg", emoji: "🐟", category: "poissonnerie" },
  { id: "108", name: "Thon frais", priceCents: 1990, unit: "kg", emoji: "🐟", category: "poissonnerie" },
  { id: "109", name: "Thon en conserve", priceCents: 190, unit: "unité", emoji: "🐟", category: "poissonnerie" },
  { id: "110", name: "Maquereau", priceCents: 290, unit: "unité", emoji: "🐟", category: "poissonnerie" },
  { id: "111", name: "Sardines fraîches", priceCents: 890, unit: "kg", emoji: "🐟", category: "poissonnerie" },
  { id: "112", name: "Sardines en boîte", priceCents: 150, unit: "unité", emoji: "🐟", category: "poissonnerie" },
  { id: "113", name: "Merlan", priceCents: 990, unit: "kg", emoji: "🐟", category: "poissonnerie" },
  { id: "114", name: "Lieu noir", priceCents: 1090, unit: "kg", emoji: "🐟", category: "poissonnerie" },
  { id: "115", name: "Sole", priceCents: 2490, unit: "kg", emoji: "🐟", category: "poissonnerie" },
  { id: "116", name: "Turbot", priceCents: 2990, unit: "kg", emoji: "🐟", category: "poissonnerie" },
  { id: "117", name: "Anchois", priceCents: 290, unit: "unité", emoji: "🐟", category: "poissonnerie" },
  { id: "118", name: "Rouget", priceCents: 1590, unit: "kg", emoji: "🐟", category: "poissonnerie" },
  { id: "119", name: "Raie", priceCents: 1390, unit: "kg", emoji: "🐟", category: "poissonnerie" },
  { id: "120", name: "Crevettes roses", priceCents: 990, unit: "unité", emoji: "🍤", category: "poissonnerie" },

  // Fromages
  { id: "121", name: "Fromage à tartiner nature", priceCents: 250, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "122", name: "Fromage à tartiner ail et fines herbes", priceCents: 260, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "123", name: "Plateau apéritif fromages", priceCents: 490, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "124", name: "Billes de mozzarella", priceCents: 220, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "125", name: "Mozzarella", priceCents: 190, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "126", name: "Burrata", priceCents: 390, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "127", name: "Feta", priceCents: 290, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "128", name: "Mascarpone", priceCents: 250, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "129", name: "Fromage frais crémeux", priceCents: 280, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "130", name: "Roquefort", priceCents: 450, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "131", name: "Bleu d'Auvergne", priceCents: 420, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "132", name: "Camembert", priceCents: 290, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "133", name: "Brie", priceCents: 350, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "134", name: "Coulommiers", priceCents: 340, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "135", name: "Bûche de chèvre", priceCents: 390, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "136", name: "Chèvre frais", priceCents: 320, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "137", name: "Brebis des Pyrénées", priceCents: 450, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "138", name: "Emmental", priceCents: 350, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "139", name: "Comté affiné", priceCents: 590, unit: "unité", emoji: "🧀", category: "fromages" },
  { id: "140", name: "Gouda", priceCents: 390, unit: "unité", emoji: "🧀", category: "fromages" },

  // Beurres, Crèmes, Margarines
  { id: "141", name: "Beurre doux", priceCents: 220, unit: "unité", emoji: "🧈", category: "beurres-cremes" },
  { id: "142", name: "Beurre demi-sel", priceCents: 230, unit: "unité", emoji: "🧈", category: "beurres-cremes" },
  { id: "143", name: "Beurre allégé", priceCents: 240, unit: "unité", emoji: "🧈", category: "beurres-cremes" },
  { id: "144", name: "Beurre de baratte", priceCents: 350, unit: "unité", emoji: "🧈", category: "beurres-cremes" },
  { id: "145", name: "Beurre bio", priceCents: 320, unit: "unité", emoji: "🧈", category: "beurres-cremes" },
  { id: "146", name: "Crème fraîche épaisse", priceCents: 190, unit: "unité", emoji: "🥛", category: "beurres-cremes" },
  { id: "147", name: "Crème fraîche légère", priceCents: 180, unit: "unité", emoji: "🥛", category: "beurres-cremes" },
  { id: "148", name: "Crème liquide entière", priceCents: 195, unit: "unité", emoji: "🥛", category: "beurres-cremes" },
  { id: "149", name: "Crème liquide allégée", priceCents: 185, unit: "unité", emoji: "🥛", category: "beurres-cremes" },
  { id: "150", name: "Crème fouettée sucrée", priceCents: 290, unit: "unité", emoji: "🥛", category: "beurres-cremes" },
  { id: "151", name: "Crème fouettée nature", priceCents: 280, unit: "unité", emoji: "🥛", category: "beurres-cremes" },
  { id: "152", name: "Chantilly en bombe", priceCents: 320, unit: "unité", emoji: "🥛", category: "beurres-cremes" },
  { id: "153", name: "Margarine tartine", priceCents: 190, unit: "unité", emoji: "🧈", category: "beurres-cremes" },
  { id: "154", name: "Margarine cuisson", priceCents: 210, unit: "unité", emoji: "🧈", category: "beurres-cremes" },
  { id: "155", name: "Margarine allégée", priceCents: 200, unit: "unité", emoji: "🧈", category: "beurres-cremes" },
  { id: "156", name: "Sauce béchamel", priceCents: 220, unit: "unité", emoji: "🥫", category: "beurres-cremes" },
  { id: "157", name: "Sauce hollandaise", priceCents: 250, unit: "unité", emoji: "🥫", category: "beurres-cremes" },
  { id: "158", name: "Sauce fromagère", priceCents: 260, unit: "unité", emoji: "🥫", category: "beurres-cremes" },
  { id: "159", name: "Sauce au poivre", priceCents: 250, unit: "unité", emoji: "🥫", category: "beurres-cremes" },
  { id: "160", name: "Sauce vinaigrette", priceCents: 190, unit: "unité", emoji: "🥫", category: "beurres-cremes" },

  // Laits et Œufs
  { id: "161", name: "Lait demi-écrémé", priceCents: 105, unit: "L", emoji: "🥛", category: "laits-oeufs" },
  { id: "162", name: "Lait entier", priceCents: 115, unit: "L", emoji: "🥛", category: "laits-oeufs" },
  { id: "163", name: "Lait écrémé", priceCents: 100, unit: "L", emoji: "🥛", category: "laits-oeufs" },
  { id: "164", name: "Lait frais du jour", priceCents: 145, unit: "L", emoji: "🥛", category: "laits-oeufs" },
  { id: "165", name: "Lait aromatisé chocolat", priceCents: 190, unit: "unité", emoji: "🥛", category: "laits-oeufs" },
  { id: "166", name: "Lait aromatisé fraise", priceCents: 190, unit: "unité", emoji: "🥛", category: "laits-oeufs" },
  { id: "167", name: "Lait bio demi-écrémé", priceCents: 165, unit: "L", emoji: "🥛", category: "laits-oeufs" },
  { id: "168", name: "Lait sans lactose", priceCents: 175, unit: "L", emoji: "🥛", category: "laits-oeufs" },
  { id: "169", name: "Lait en poudre", priceCents: 490, unit: "unité", emoji: "🥛", category: "laits-oeufs" },
  { id: "170", name: "Lait concentré sucré", priceCents: 290, unit: "unité", emoji: "🥛", category: "laits-oeufs" },
  { id: "171", name: "Lait concentré non sucré", priceCents: 190, unit: "unité", emoji: "🥛", category: "laits-oeufs" },
  { id: "172", name: "Lait de chèvre", priceCents: 250, unit: "L", emoji: "🥛", category: "laits-oeufs" },
  { id: "173", name: "Œufs plein air (x6)", priceCents: 250, unit: "unité", emoji: "🥚", category: "laits-oeufs" },
  { id: "174", name: "Œufs plein air (x12)", priceCents: 350, unit: "unité", emoji: "🥚", category: "laits-oeufs" },
  { id: "175", name: "Œufs bio (x6)", priceCents: 350, unit: "unité", emoji: "🥚", category: "laits-oeufs" },
  { id: "176", name: "Œufs bio (x12)", priceCents: 490, unit: "unité", emoji: "🥚", category: "laits-oeufs" },
  { id: "177", name: "Œufs extra frais (x6)", priceCents: 260, unit: "unité", emoji: "🥚", category: "laits-oeufs" },
  { id: "178", name: "Œufs de caille", priceCents: 290, unit: "unité", emoji: "🥚", category: "laits-oeufs" },
  { id: "179", name: "Blancs d'œufs liquides", priceCents: 290, unit: "unité", emoji: "🥚", category: "laits-oeufs" },
  { id: "180", name: "Œufs durs prêts à consommer", priceCents: 250, unit: "unité", emoji: "🥚", category: "laits-oeufs" },

  // Yaourts, Fromages blancs
  { id: "181", name: "Yaourts nature allégés (x8)", priceCents: 240, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "182", name: "Skyr nature", priceCents: 320, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "183", name: "Yaourts bio nature (x8)", priceCents: 290, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "184", name: "Fromage blanc 0%", priceCents: 210, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "185", name: "Fromage blanc entier", priceCents: 220, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "186", name: "Petits suisses nature (x12)", priceCents: 190, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "187", name: "Petits suisses aux fruits (x12)", priceCents: 210, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "188", name: "Fromage blanc fruits rouges", priceCents: 250, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "189", name: "Fromage blanc vanille", priceCents: 240, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "190", name: "Yaourts à la grecque", priceCents: 320, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "191", name: "Yaourts façon fermier", priceCents: 290, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "192", name: "Yaourt à boire fraise", priceCents: 250, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "193", name: "Yaourt à boire nature", priceCents: 230, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "194", name: "Yaourts aromatisés vanille (x8)", priceCents: 270, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "195", name: "Yaourts aux fruits mélangés (x8)", priceCents: 280, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "196", name: "Yaourts à la myrtille (x8)", priceCents: 280, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "197", name: "Yaourts bifidus nature (x8)", priceCents: 290, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "198", name: "Yaourts bifidus aux fruits (x8)", priceCents: 300, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "199", name: "Yaourts natures sucrés (x8)", priceCents: 260, unit: "unité", emoji: "🍦", category: "yaourts" },
  { id: "200", name: "Faisselle", priceCents: 210, unit: "unité", emoji: "🍦", category: "yaourts" },

  // Desserts
  { id: "201", name: "Compote pomme nature", priceCents: 220, unit: "unité", emoji: "🍏", category: "desserts" },
  { id: "202", name: "Compote pomme-fraise", priceCents: 230, unit: "unité", emoji: "🍓", category: "desserts" },
  { id: "203", name: "Compote pomme-banane", priceCents: 230, unit: "unité", emoji: "🍌", category: "desserts" },
  { id: "204", name: "Crème aux œufs", priceCents: 260, unit: "unité", emoji: "🍮", category: "desserts" },
  { id: "205", name: "Crème caramel", priceCents: 260, unit: "unité", emoji: "🍮", category: "desserts" },
  { id: "206", name: "Crème dessert vanille", priceCents: 250, unit: "unité", emoji: "🍮", category: "desserts" },
  { id: "207", name: "Crème dessert chocolat", priceCents: 250, unit: "unité", emoji: "🍮", category: "desserts" },
  { id: "208", name: "Dessert gourmand chocolat-caramel", priceCents: 290, unit: "unité", emoji: "🍰", category: "desserts" },
  { id: "209", name: "Dessert gourmand spéculoos", priceCents: 290, unit: "unité", emoji: "🍰", category: "desserts" },
  { id: "210", name: "Flan pâtissier", priceCents: 290, unit: "unité", emoji: "🍮", category: "desserts" },
  { id: "211", name: "Flan nappé caramel", priceCents: 270, unit: "unité", emoji: "🍮", category: "desserts" },
  { id: "212", name: "Goûter fourré chocolat", priceCents: 250, unit: "unité", emoji: "🧁", category: "desserts" },
  { id: "213", name: "Goûter aux fruits", priceCents: 240, unit: "unité", emoji: "🧁", category: "desserts" },
  { id: "214", name: "Liégeois chocolat", priceCents: 280, unit: "unité", emoji: "🍨", category: "desserts" },
  { id: "215", name: "Liégeois café", priceCents: 280, unit: "unité", emoji: "🍨", category: "desserts" },
  { id: "216", name: "Mousse au chocolat", priceCents: 270, unit: "unité", emoji: "🍫", category: "desserts" },
  { id: "217", name: "Mousse au citron", priceCents: 270, unit: "unité", emoji: "🍋", category: "desserts" },
  { id: "218", name: "Riz au lait", priceCents: 260, unit: "unité", emoji: "🍚", category: "desserts" },
  { id: "219", name: "Teurgoule", priceCents: 290, unit: "unité", emoji: "🍚", category: "desserts" },
  { id: "220", name: "Semoule au lait", priceCents: 250, unit: "unité", emoji: "🍚", category: "desserts" },

  // Épicerie salée
  { id: "221", name: "Spaghetti", priceCents: 130, unit: "unité", emoji: "🍝", category: "epicerie-salee" },
  { id: "222", name: "Penne", priceCents: 130, unit: "unité", emoji: "🍝", category: "epicerie-salee" },
  { id: "223", name: "Coquillettes", priceCents: 130, unit: "unité", emoji: "🍝", category: "epicerie-salee" },
  { id: "224", name: "Tagliatelles", priceCents: 150, unit: "unité", emoji: "🍝", category: "epicerie-salee" },
  { id: "225", name: "Lasagnes", priceCents: 190, unit: "unité", emoji: "🍝", category: "epicerie-salee" },
  { id: "226", name: "Riz basmati", priceCents: 250, unit: "kg", emoji: "🍚", category: "epicerie-salee" },
  { id: "227", name: "Riz rond", priceCents: 220, unit: "kg", emoji: "🍚", category: "epicerie-salee" },
  { id: "228", name: "Riz complet", priceCents: 260, unit: "kg", emoji: "🍚", category: "epicerie-salee" },
  { id: "229", name: "Semoule", priceCents: 190, unit: "kg", emoji: "🍚", category: "epicerie-salee" },
  { id: "230", name: "Quinoa", priceCents: 490, unit: "kg", emoji: "🍚", category: "epicerie-salee" },
  { id: "231", name: "Lentilles vertes", priceCents: 290, unit: "kg", emoji: "🫘", category: "epicerie-salee" },
  { id: "232", name: "Lentilles corail", priceCents: 310, unit: "kg", emoji: "🫘", category: "epicerie-salee" },
  { id: "233", name: "Pois chiches", priceCents: 260, unit: "kg", emoji: "🫘", category: "epicerie-salee" },
  { id: "234", name: "Haricots blancs", priceCents: 250, unit: "kg", emoji: "🫘", category: "epicerie-salee" },
  { id: "235", name: "Huile d'olive", priceCents: 490, unit: "unité", emoji: "🫒", category: "epicerie-salee" },
  { id: "236", name: "Huile de tournesol", priceCents: 290, unit: "unité", emoji: "🫒", category: "epicerie-salee" },
  { id: "237", name: "Huile de colza", priceCents: 320, unit: "unité", emoji: "🫒", category: "epicerie-salee" },
  { id: "238", name: "Vinaigre balsamique", priceCents: 390, unit: "unité", emoji: "🍶", category: "epicerie-salee" },
  { id: "239", name: "Vinaigre de vin", priceCents: 190, unit: "unité", emoji: "🍶", category: "epicerie-salee" },
  { id: "240", name: "Moutarde", priceCents: 190, unit: "unité", emoji: "🌭", category: "epicerie-salee" },

  // Conserves
  { id: "241", name: "Tomates pelées", priceCents: 110, unit: "unité", emoji: "🥫", category: "conserves" },
  { id: "242", name: "Concentré de tomates", priceCents: 130, unit: "unité", emoji: "🥫", category: "conserves" },
  { id: "243", name: "Haricots verts", priceCents: 130, unit: "unité", emoji: "🥫", category: "conserves" },
  { id: "244", name: "Haricots rouges", priceCents: 140, unit: "unité", emoji: "🥫", category: "conserves" },
  { id: "245", name: "Maïs doux", priceCents: 140, unit: "unité", emoji: "🌽", category: "conserves" },
  { id: "246", name: "Petits pois", priceCents: 120, unit: "unité", emoji: "🥫", category: "conserves" },
  { id: "247", name: "Thon au naturel", priceCents: 190, unit: "unité", emoji: "🐟", category: "conserves" },
  { id: "248", name: "Thon à l'huile", priceCents: 195, unit: "unité", emoji: "🐟", category: "conserves" },
  { id: "249", name: "Sardines à l'huile", priceCents: 150, unit: "unité", emoji: "🐟", category: "conserves" },
  { id: "250", name: "Maquereaux à la moutarde", priceCents: 170, unit: "unité", emoji: "🐟", category: "conserves" },
  { id: "251", name: "Champignons de Paris", priceCents: 150, unit: "unité", emoji: "🍄", category: "conserves" },
  { id: "252", name: "Cœurs de palmier", priceCents: 250, unit: "unité", emoji: "🥫", category: "conserves" },
  { id: "253", name: "Artichauts", priceCents: 290, unit: "unité", emoji: "🥫", category: "conserves" },
  { id: "254", name: "Asperges", priceCents: 290, unit: "unité", emoji: "🥫", category: "conserves" },
  { id: "255", name: "Betteraves cuites", priceCents: 150, unit: "unité", emoji: "🥫", category: "conserves" },
  { id: "256", name: "Choucroute", priceCents: 220, unit: "unité", emoji: "🥫", category: "conserves" },
  { id: "257", name: "Cassoulet", priceCents: 350, unit: "unité", emoji: "🥫", category: "conserves" },
  { id: "258", name: "Chili con carne", priceCents: 350, unit: "unité", emoji: "🥫", category: "conserves" },
  { id: "259", name: "Ravioli en boîte", priceCents: 190, unit: "unité", emoji: "🥫", category: "conserves" },
  { id: "260", name: "Petits pois carottes", priceCents: 130, unit: "unité", emoji: "🥫", category: "conserves" },

  // Épicerie sucrée
  { id: "261", name: "Sucre en poudre", priceCents: 160, unit: "kg", emoji: "🍬", category: "epicerie-sucree" },
  { id: "262", name: "Sucre roux", priceCents: 190, unit: "kg", emoji: "🍬", category: "epicerie-sucree" },
  { id: "263", name: "Sucre glace", priceCents: 150, unit: "unité", emoji: "🍬", category: "epicerie-sucree" },
  { id: "264", name: "Sucre vanillé", priceCents: 90, unit: "unité", emoji: "🍬", category: "epicerie-sucree" },
  { id: "265", name: "Miel", priceCents: 490, unit: "unité", emoji: "🍯", category: "epicerie-sucree" },
  { id: "266", name: "Confiture de fraise", priceCents: 290, unit: "unité", emoji: "🍓", category: "epicerie-sucree" },
  { id: "267", name: "Confiture d'abricot", priceCents: 290, unit: "unité", emoji: "🍑", category: "epicerie-sucree" },
  { id: "268", name: "Confiture de framboise", priceCents: 310, unit: "unité", emoji: "🍓", category: "epicerie-sucree" },
  { id: "269", name: "Nutella", priceCents: 490, unit: "unité", emoji: "🍫", category: "epicerie-sucree" },
  { id: "270", name: "Pâte à tartiner noisette", priceCents: 350, unit: "unité", emoji: "🍫", category: "epicerie-sucree" },
  { id: "271", name: "Chocolat noir", priceCents: 250, unit: "unité", emoji: "🍫", category: "epicerie-sucree" },
  { id: "272", name: "Chocolat au lait", priceCents: 250, unit: "unité", emoji: "🍫", category: "epicerie-sucree" },
  { id: "273", name: "Chocolat blanc", priceCents: 260, unit: "unité", emoji: "🍫", category: "epicerie-sucree" },
  { id: "274", name: "Pépites de chocolat", priceCents: 290, unit: "unité", emoji: "🍫", category: "epicerie-sucree" },
  { id: "275", name: "Céréales chocolatées", priceCents: 340, unit: "unité", emoji: "🥣", category: "epicerie-sucree" },
  { id: "276", name: "Céréales muesli", priceCents: 350, unit: "unité", emoji: "🥣", category: "epicerie-sucree" },
  { id: "277", name: "Céréales flocons d'avoine", priceCents: 250, unit: "unité", emoji: "🥣", category: "epicerie-sucree" },
  { id: "278", name: "Barres de céréales", priceCents: 290, unit: "unité", emoji: "🍫", category: "epicerie-sucree" },
  { id: "279", name: "Biscuits sablés", priceCents: 210, unit: "unité", emoji: "🍪", category: "epicerie-sucree" },
  { id: "280", name: "Biscuits chocolat", priceCents: 230, unit: "unité", emoji: "🍪", category: "epicerie-sucree" },

  // Boissons
  { id: "281", name: "Café moulu", priceCents: 550, unit: "unité", emoji: "☕", category: "boissons" },
  { id: "282", name: "Café en grains", priceCents: 690, unit: "unité", emoji: "☕", category: "boissons" },
  { id: "283", name: "Café en capsules", priceCents: 590, unit: "unité", emoji: "☕", category: "boissons" },
  { id: "284", name: "Thé noir", priceCents: 350, unit: "unité", emoji: "🍵", category: "boissons" },
  { id: "285", name: "Thé vert", priceCents: 390, unit: "unité", emoji: "🍵", category: "boissons" },
  { id: "286", name: "Infusion tilleul", priceCents: 320, unit: "unité", emoji: "🍵", category: "boissons" },
  { id: "287", name: "Chocolat en poudre boisson", priceCents: 350, unit: "unité", emoji: "🍫", category: "boissons" },
  { id: "288", name: "Eau plate (pack 6)", priceCents: 300, unit: "unité", emoji: "💧", category: "boissons" },
  { id: "289", name: "Eau gazeuse (pack 6)", priceCents: 350, unit: "unité", emoji: "💧", category: "boissons" },
  { id: "290", name: "Eau minérale 1.5L", priceCents: 90, unit: "unité", emoji: "💧", category: "boissons" },
  { id: "291", name: "Jus d'orange", priceCents: 240, unit: "unité", emoji: "🧃", category: "boissons" },
  { id: "292", name: "Jus de pomme", priceCents: 230, unit: "unité", emoji: "🧃", category: "boissons" },
  { id: "293", name: "Jus de raisin", priceCents: 250, unit: "unité", emoji: "🧃", category: "boissons" },
  { id: "294", name: "Jus multifruits", priceCents: 240, unit: "unité", emoji: "🧃", category: "boissons" },
  { id: "295", name: "Jus de tomate", priceCents: 230, unit: "unité", emoji: "🧃", category: "boissons" },
  { id: "296", name: "Nectar d'abricot", priceCents: 230, unit: "unité", emoji: "🧃", category: "boissons" },
  { id: "297", name: "Soda cola", priceCents: 190, unit: "unité", emoji: "🥤", category: "boissons" },
  { id: "298", name: "Soda citron", priceCents: 190, unit: "unité", emoji: "🥤", category: "boissons" },
  { id: "299", name: "Soda orange", priceCents: 190, unit: "unité", emoji: "🥤", category: "boissons" },
  { id: "300", name: "Limonade", priceCents: 180, unit: "unité", emoji: "🥤", category: "boissons" },

  // Surgelés
  { id: "301", name: "Frites surgelées", priceCents: 260, unit: "unité", emoji: "🍟", category: "surgeles" },
  { id: "302", name: "Wedges surgelées", priceCents: 280, unit: "unité", emoji: "🍟", category: "surgeles" },
  { id: "303", name: "Purée surgelée", priceCents: 250, unit: "unité", emoji: "🥔", category: "surgeles" },
  { id: "304", name: "Légumes surgelés mélangés", priceCents: 220, unit: "unité", emoji: "🧊", category: "surgeles" },
  { id: "305", name: "Épinards surgelés", priceCents: 210, unit: "unité", emoji: "🥬", category: "surgeles" },
  { id: "306", name: "Petits pois surgelés", priceCents: 200, unit: "unité", emoji: "🫛", category: "surgeles" },
  { id: "307", name: "Haricots verts surgelés", priceCents: 220, unit: "unité", emoji: "🫛", category: "surgeles" },
  { id: "308", name: "Brocoli surgelé", priceCents: 230, unit: "unité", emoji: "🥦", category: "surgeles" },
  { id: "309", name: "Ratatouille surgelée", priceCents: 250, unit: "unité", emoji: "🍆", category: "surgeles" },
  { id: "310", name: "Pizza surgelée", priceCents: 390, unit: "unité", emoji: "🍕", category: "surgeles" },
  { id: "311", name: "Quiche surgelée", priceCents: 350, unit: "unité", emoji: "🥧", category: "surgeles" },
  { id: "312", name: "Lasagnes surgelées", priceCents: 390, unit: "unité", emoji: "🍝", category: "surgeles" },
  { id: "313", name: "Poêlée de légumes", priceCents: 280, unit: "unité", emoji: "🧊", category: "surgeles" },
  { id: "314", name: "Glace vanille", priceCents: 390, unit: "unité", emoji: "🍨", category: "surgeles" },
  { id: "315", name: "Glace chocolat", priceCents: 390, unit: "unité", emoji: "🍨", category: "surgeles" },
  { id: "316", name: "Glace fraise", priceCents: 390, unit: "unité", emoji: "🍨", category: "surgeles" },
  { id: "317", name: "Sorbet citron", priceCents: 350, unit: "unité", emoji: "🍧", category: "surgeles" },
  { id: "318", name: "Bâtonnets glacés", priceCents: 350, unit: "unité", emoji: "🍦", category: "surgeles" },
  { id: "319", name: "Cônes glacés", priceCents: 390, unit: "unité", emoji: "🍦", category: "surgeles" },
  { id: "320", name: "Tarte glacée", priceCents: 490, unit: "unité", emoji: "🍰", category: "surgeles" },

  // Hygiène & Beauté
  { id: "321", name: "Savon solide", priceCents: 180, unit: "unité", emoji: "🧼", category: "hygiene" },
  { id: "322", name: "Gel douche", priceCents: 290, unit: "unité", emoji: "🧴", category: "hygiene" },
  { id: "323", name: "Shampoing", priceCents: 390, unit: "unité", emoji: "🧴", category: "hygiene" },
  { id: "324", name: "Après-shampoing", priceCents: 390, unit: "unité", emoji: "🧴", category: "hygiene" },
  { id: "325", name: "Dentifrice", priceCents: 250, unit: "unité", emoji: "🪥", category: "hygiene" },
  { id: "326", name: "Brosse à dents", priceCents: 190, unit: "unité", emoji: "🪥", category: "hygiene" },
  { id: "327", name: "Bain de bouche", priceCents: 350, unit: "unité", emoji: "🧴", category: "hygiene" },
  { id: "328", name: "Fil dentaire", priceCents: 190, unit: "unité", emoji: "🧵", category: "hygiene" },
  { id: "329", name: "Déodorant", priceCents: 350, unit: "unité", emoji: "🧴", category: "hygiene" },
  { id: "330", name: "Mousse à raser", priceCents: 290, unit: "unité", emoji: "🪒", category: "hygiene" },
  { id: "331", name: "Rasoirs jetables", priceCents: 350, unit: "unité", emoji: "🪒", category: "hygiene" },
  { id: "332", name: "Crème hydratante", priceCents: 490, unit: "unité", emoji: "🧴", category: "hygiene" },
  { id: "333", name: "Lait corporel", priceCents: 390, unit: "unité", emoji: "🧴", category: "hygiene" },
  { id: "334", name: "Crème solaire", priceCents: 690, unit: "unité", emoji: "🧴", category: "hygiene" },
  { id: "335", name: "Coton-tiges", priceCents: 190, unit: "unité", emoji: "🧴", category: "hygiene" },
  { id: "336", name: "Cotons démaquillants", priceCents: 220, unit: "unité", emoji: "🧴", category: "hygiene" },
  { id: "337", name: "Lingettes démaquillantes", priceCents: 350, unit: "unité", emoji: "🧴", category: "hygiene" },
  { id: "338", name: "Mouchoirs en papier", priceCents: 190, unit: "unité", emoji: "🧻", category: "hygiene" },
  { id: "339", name: "Papier toilette (x12)", priceCents: 690, unit: "unité", emoji: "🧻", category: "hygiene" },
  { id: "340", name: "Serviettes hygiéniques", priceCents: 290, unit: "unité", emoji: "🧴", category: "hygiene" },

  // Entretien
  { id: "341", name: "Lessive liquide", priceCents: 690, unit: "unité", emoji: "🧺", category: "entretien" },
  { id: "342", name: "Lessive en poudre", priceCents: 590, unit: "unité", emoji: "🧺", category: "entretien" },
  { id: "343", name: "Capsules de lessive", priceCents: 790, unit: "unité", emoji: "🧺", category: "entretien" },
  { id: "344", name: "Adoucissant", priceCents: 390, unit: "unité", emoji: "🧺", category: "entretien" },
  { id: "345", name: "Détachant", priceCents: 350, unit: "unité", emoji: "🧺", category: "entretien" },
  { id: "346", name: "Nettoyant vitres", priceCents: 290, unit: "unité", emoji: "🪟", category: "entretien" },
  { id: "347", name: "Nettoyant multi-usage", priceCents: 290, unit: "unité", emoji: "🧽", category: "entretien" },
  { id: "348", name: "Nettoyant sol", priceCents: 350, unit: "unité", emoji: "🧽", category: "entretien" },
  { id: "349", name: "Eau de Javel", priceCents: 220, unit: "unité", emoji: "🧴", category: "entretien" },
  { id: "350", name: "Vinaigre blanc", priceCents: 190, unit: "unité", emoji: "🧴", category: "entretien" },
  { id: "351", name: "Bicarbonate de soude", priceCents: 190, unit: "unité", emoji: "🧴", category: "entretien" },
  { id: "352", name: "Liquide vaisselle", priceCents: 250, unit: "unité", emoji: "🧴", category: "entretien" },
  { id: "353", name: "Tablettes lave-vaisselle", priceCents: 590, unit: "unité", emoji: "🍽️", category: "entretien" },
  { id: "354", name: "Sel pour lave-vaisselle", priceCents: 350, unit: "unité", emoji: "🍽️", category: "entretien" },
  { id: "355", name: "Liquide de rinçage", priceCents: 350, unit: "unité", emoji: "🍽️", category: "entretien" },
  { id: "356", name: "Éponges", priceCents: 150, unit: "unité", emoji: "🧽", category: "entretien" },
  { id: "357", name: "Gants de ménage", priceCents: 190, unit: "unité", emoji: "🧤", category: "entretien" },
  { id: "358", name: "Serpillière", priceCents: 350, unit: "unité", emoji: "🧹", category: "entretien" },
  { id: "359", name: "Balai", priceCents: 690, unit: "unité", emoji: "🧹", category: "entretien" },
  { id: "360", name: "Pelle et balayette", priceCents: 490, unit: "unité", emoji: "🧹", category: "entretien" },

  // Boulangerie
  { id: "361", name: "Baguette tradition", priceCents: 120, unit: "unité", emoji: "🥖", category: "boulangerie" },
  { id: "362", name: "Baguette classique", priceCents: 110, unit: "unité", emoji: "🥖", category: "boulangerie" },
  { id: "363", name: "Pain de campagne", priceCents: 250, unit: "unité", emoji: "🍞", category: "boulangerie" },
  { id: "364", name: "Pain complet", priceCents: 260, unit: "unité", emoji: "🍞", category: "boulangerie" },
  { id: "365", name: "Pain aux céréales", priceCents: 280, unit: "unité", emoji: "🍞", category: "boulangerie" },
  { id: "366", name: "Pain de mie", priceCents: 190, unit: "unité", emoji: "🍞", category: "boulangerie" },
  { id: "367", name: "Pain de mie complet", priceCents: 210, unit: "unité", emoji: "🍞", category: "boulangerie" },
  { id: "368", name: "Pain sans gluten", priceCents: 390, unit: "unité", emoji: "🍞", category: "boulangerie" },
  { id: "369", name: "Croissants (x4)", priceCents: 320, unit: "unité", emoji: "🥐", category: "boulangerie" },
  { id: "370", name: "Pains au chocolat (x4)", priceCents: 350, unit: "unité", emoji: "🥐", category: "boulangerie" },
  { id: "371", name: "Chaussons aux pommes", priceCents: 290, unit: "unité", emoji: "🥐", category: "boulangerie" },
  { id: "372", name: "Brioche", priceCents: 290, unit: "unité", emoji: "🍞", category: "boulangerie" },
  { id: "373", name: "Brioche tressée", priceCents: 350, unit: "unité", emoji: "🍞", category: "boulangerie" },
  { id: "374", name: "Pain aux raisins", priceCents: 300, unit: "unité", emoji: "🥐", category: "boulangerie" },
  { id: "375", name: "Fougasse", priceCents: 290, unit: "unité", emoji: "🍞", category: "boulangerie" },
  { id: "376", name: "Pain bagnat", priceCents: 350, unit: "unité", emoji: "🥖", category: "boulangerie" },
  { id: "377", name: "Pain burger", priceCents: 250, unit: "unité", emoji: "🍔", category: "boulangerie" },
  { id: "378", name: "Pain hot-dog", priceCents: 220, unit: "unité", emoji: "🌭", category: "boulangerie" },
  { id: "379", name: "Petit pain", priceCents: 90, unit: "unité", emoji: "🍞", category: "boulangerie" },
  { id: "380", name: "Ficelle", priceCents: 100, unit: "unité", emoji: "🥖", category: "boulangerie" },

];